language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t renrobles/docker-react-course -f Dockerfile.dev .

script:
  - docker run -e CI=true renrobles/docker-react-course npm run test