language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t renrobles/docker-react-course -f Dockerfile.dev .

script:
  - docker run -e CI=true renrobles/docker-react-course npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-course"
  env: "DockerReactCourse-env"
  bucket_name: "elasticbeanstalk-us-east-2-739263153345"
  bucket_path: "docker-react-course"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY